### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [calvinwilliams/cocker#8]
I would like to point out that identifiers like “[`__container`](https://github.com/calvinwilliams/cocker/blob/5ddbcb69454cfbb42546028e51ff85fb96058ccf/src/cocker/cocker_in.h#L27)” and “[`_H_FILERPL_`](https://github.com/calvinwilliams/cocker/blob/58311a8c876403ed76328673adf9960dc1eafbf7/src/util/filerpl.h#L1)” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by calvinwilliams** [comment]
Thanks , but it's my company's code style standard , I've accepted it .

**Comment by elfring** [comment]
How do you (including the company) think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by elfring** [comment]
Would you like to [stop tampering with the reserved name space](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
